[platformio]
default_envs = stable

[env:stable]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/51.03.07/platform-espressif32.zip
framework = arduino
lib_extra_dirs = ~/Arduino/libraries
lib_deps =
    https://github.com/collin80/esp32_can.git
    https://github.com/collin80/esp32_mcp2517fd.git
    https://github.com/collin80/can_common.git
    fastled/FastLED@^3.6.0

;for ESP32 boards (16MB flash)
board = esp32dev
board_build.partitions = default_16MB.csv
board_build.flash_size = 16MB
board_upload.flash_size = 16MB
;enable max debugging
build_flags = -DCORE_DEBUG_LEVEL=5


[env:stable-s3]
;this one is probably fine to attempt to keep up to date.
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.34/platform-espressif32.zip
framework = arduino
lib_extra_dirs = ~/Arduino/libraries
lib_deps =
    https://github.com/collin80/esp32_can.git
    https://github.com/collin80/esp32_mcp2517fd.git
    https://github.com/collin80/can_common.git
    fastled/FastLED@^3.6.0

;for ESP32-S3 boards (8MB flash)
board_build.partitions = app_s3.csv
board = esp32-s3-devkitc-1
;enable max debugging and set so that Serial is the USB port and automatically started on boot
build_flags = -DCORE_DEBUG_LEVEL=5 -D ARDUINO_USB_MODE=1 -D ARDUINO_USB_CDC_ON_BOOT=1
